name: My First Workflow

on: push

jobs:
  say-hello:
    runs-on: ubuntu-latest

    steps:
      - name: Print Hello Message
        run: echo "Hello, Vibhor"

      - name: Print Bye Message
        run: echo "Bye GitHub"